name: Format code

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Format code
    if: "!startsWith(github.ref, 'refs/heads/ci')"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get current branch name
        id: get_branch
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Format code
        run: find ./projects -type f \( -name "*.cpp" -o -name "*.h" -o -name "*.glsl" \) | xargs clang-format -i

      - name: Show git status
        run: git status

      - name: Create new pull request if necessary
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Format code for ${{ env.branch_name }}
          branch: ci/format/${{ env.branch_name }}
          commit-message: Format code for ${{ env.branch_name }}
